server:
  port: 8081

com.griddynamics.product.indexer:
  esHost: http://localhost:9200
  user: elastic
  pass: Qo4dba5o1aH7qE7mfUoI
  index: product_index

  files:
    mappings: classpath:elastic/mappings.json
    settings: classpath:elastic/settings.json
    data:     classpath:elastic/task8_data.json

